// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUu4YOSqnk3qaqpnTd34VShm2LFgrJrrc',
    appId: '1:739635523335:web:7b0178d7779d3cc9529fa2',
    messagingSenderId: '739635523335',
    projectId: 'new-zik',
    authDomain: 'new-zik.firebaseapp.com',
    databaseURL: 'https://new-zik-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'new-zik.appspot.com',
    measurementId: 'G-ZLR4D2C47K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkB2gWpGBzv2W4UmX0g_TFB3Btu8_KWhY',
    appId: '1:739635523335:android:bf509d8f3aeebbc0529fa2',
    messagingSenderId: '739635523335',
    projectId: 'new-zik',
    databaseURL: 'https://new-zik-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'new-zik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu5u01zdpfuqdUVvFfgGx1Lny2LvN2uwk',
    appId: '1:739635523335:ios:39548d8f5ed5a363529fa2',
    messagingSenderId: '739635523335',
    projectId: 'new-zik',
    databaseURL: 'https://new-zik-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'new-zik.appspot.com',
    iosClientId: '739635523335-egugrn1fai4dkd7ttrgj9cqm9n3rtqs3.apps.googleusercontent.com',
    iosBundleId: 'com.newzik.app',
  );
}
